const { app, BrowserWindow, ipcMain, dialog } = require('electron');
const path = require('node:path');
const fs = require('node:fs');
const ExcelJS = require('exceljs');

let dataDir, bookPath;
const sheets = { Workers:'workers', Products:'products', Production:'production', Debts:'debts', Payments:'payments', Periods:'periods', Audit:'audit' };
const blank = () => ({ workers:[], products:[], production:[], debts:[], payments:[], periods:[], audit:[] });
async function readBook() {
  if (!fs.existsSync(bookPath)) return blank();
  try { const wb = new ExcelJS.Workbook(); await wb.xlsx.readFile(bookPath); const result = blank(); for (const [sheet,key] of Object.entries(sheets)) { const ws=wb.getWorksheet(sheet); if(!ws)continue; const headers=ws.getRow(1).values.slice(1).map(x=>String(x??'')); ws.eachRow((row,rowNumber)=>{if(rowNumber===1)return;const item={};headers.forEach((header,index)=>{if(header)item[header]=row.getCell(index+1).value??''});if(Object.keys(item).length){if(key==='debts'&&!item.direction)item.direction='WORKER_OWES';result[key].push(item)} }); } return result; }
  catch(e) { throw new Error('Không đọc được file Excel. Hãy đóng file đang mở và kiểm tra file dữ liệu. ' + e.message); }
}
const headers={workers:['id','name','createdAt','status'],products:['id','name','currentPrice','status','createdAt'],production:['id','workerId','productId','productName','date','quantity','unitPrice','totalAmount','periodId','status'],debts:['id','workerId','date','amount','note','direction','status','paymentId'],payments:['id','workerId','paymentDate','productionTotal','debtDeducted','companyDebtAdded','actualReceived','periodId'],periods:['id','workerId','startDate','endDate','status','fileName'],audit:['id','at','action','entity','before','after']};
async function writeBook(data) {
  fs.mkdirSync(dataDir,{recursive:true});
  const wb=new ExcelJS.Workbook();
  for (const [sheet,key] of Object.entries(sheets)) { const ws=wb.addWorksheet(sheet),columns=headers[key];ws.addRow(columns);for(const item of data[key]||[])ws.addRow(columns.map(column=>item[column]??'')); }
  const temp=bookPath+'.tmp.xlsx';
  try { await wb.xlsx.writeFile(temp); fs.renameSync(temp,bookPath); }
  catch(e) { try{if(fs.existsSync(temp))fs.unlinkSync(temp)}catch{}; throw new Error('Không thể ghi dữ liệu vào Excel. Vui lòng đóng file Excel đang mở và thử lại. '+e.message); }
}
const id = prefix => `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
const today = () => {const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const isPaid = p => p.status === 'PAID';
function audit(data,action,entity,before,after){data.audit.push({id:id('LOG'),at:new Date().toISOString(),action,entity,before:JSON.stringify(before||{}),after:JSON.stringify(after||{})});}
function periodFor(data,workerId,date){let p=data.periods.find(x=>x.workerId===workerId&&x.status==='OPEN'); if(!p){p={id:id('DOT'),workerId,startDate:date,endDate:date,status:'OPEN',fileName:''};data.periods.push(p)}else {if(!p.startDate||date<p.startDate)p.startDate=date;if(!p.endDate||date>p.endDate)p.endDate=date;}return p;}
function updatePeriodDates(data,periodId){const p=data.periods.find(x=>x.id===periodId); if(!p)return; const dates=data.production.filter(x=>x.periodId===periodId).map(x=>x.date).sort(); p.startDate=dates[0]||'';p.endDate=dates.at(-1)||'' }
async function exportPeriod(data,payment){
  const p=data.periods.find(x=>x.id===payment.periodId),worker=data.workers.find(x=>x.id===payment.workerId);
  if(!p||!worker)return;
  const folder=path.join(dataDir,'Luong',slug(worker.name));fs.mkdirSync(folder,{recursive:true});
  const baseFilename=`Dot-${vnDate(p.startDate)}_${vnDate(p.endDate)}`;
  let filename=`${baseFilename}.xlsx`,filePath=path.join(folder,filename),version=2;
  // Excel khóa file đang mở; xuất bản mới thay vì ghi đè để tránh lỗi EBUSY.
  while(fs.existsSync(filePath)){filename=`${baseFilename}_${version++}.xlsx`;filePath=path.join(folder,filename)}
  p.fileName=filename;
  const wb=new ExcelJS.Workbook(),companyDebtAdded=Number(payment.companyDebtAdded)||0;
  const prod=data.production.filter(x=>x.periodId===p.id).map(x=>({Ngày:x.date,Sản_phẩm:x.productName,Số_lượng:Number(x.quantity),Đơn_giá:Number(x.unitPrice),Thành_tiền:Number(x.totalAmount),Trạng_thái:x.status}));
  prod.push(
    {Ngày:'',Sản_phẩm:'',Số_lượng:'',Đơn_giá:'',Thành_tiền:'',Trạng_thái:''},
    {Ngày:'',Sản_phẩm:'TỔNG TIỀN SẢN XUẤT',Số_lượng:'',Đơn_giá:'',Thành_tiền:Number(payment.productionTotal),Trạng_thái:''},
    {Ngày:'',Sản_phẩm:'NỢ KỸ SƯ ĐÃ TRỪ',Số_lượng:'',Đơn_giá:'',Thành_tiền:-Number(payment.debtDeducted),Trạng_thái:''},
    {Ngày:'',Sản_phẩm:'NỢ CÔNG TY CỘNG THÊM',Số_lượng:'',Đơn_giá:'',Thành_tiền:companyDebtAdded,Trạng_thái:''},
    {Ngày:'',Sản_phẩm:'THỰC NHẬN',Số_lượng:'',Đơn_giá:'',Thành_tiền:Number(payment.actualReceived),Trạng_thái:''},
  );
  // Chỉ xuất các khoản nợ đã được tất toán trong giao dịch này, tránh lẫn nợ còn treo.
  const debts=data.debts.filter(x=>x.paymentId===payment.id).map(x=>({Ngày:x.date,Hướng_công_nợ:x.direction==='COMPANY_OWES'?'Công ty nợ Kỹ sư':'Kỹ sư nợ Công ty',Ghi_chú:x.note,Số_tiền:Number(x.amount),Xử_lý:x.direction==='COMPANY_OWES'?'Cộng vào lương':'Trừ vào lương',Trạng_thái:x.status==='DA_TRA'?'Đã cộng':'Đã trừ'}));
  const summary={'Kỹ sư':worker.name,'Từ ngày':p.startDate,'Đến ngày':p.endDate,'Ngày thanh toán':payment.paymentDate,'Tổng lương sản phẩm':Number(payment.productionTotal),'Nợ Kỹ sư đã trừ':Number(payment.debtDeducted),'Nợ Công ty cộng thêm':companyDebtAdded,'Thực nhận':Number(payment.actualReceived),'Cách tính':'Tổng lương - Nợ Kỹ sư đã trừ + Nợ Công ty cộng thêm'};
  const paymentRow={'Mã giao dịch':payment.id,'Kỹ sư':worker.name,'Ngày thanh toán':payment.paymentDate,'Tổng lương sản phẩm':Number(payment.productionTotal),'Nợ Kỹ sư đã trừ':Number(payment.debtDeducted),'Nợ Công ty cộng thêm':companyDebtAdded,'Thực nhận':Number(payment.actualReceived)};
  addSheet(wb,'Production',prod);addSheet(wb,'Payment',[paymentRow]);addSheet(wb,'Debt',debts);addSheet(wb,'Summary',[summary]);
  // Mở workbook ở sheet tổng kết để thông tin thanh toán hiện ra ngay.
  wb.views=[{firstSheet:0,activeTab:3,visibility:'visible'}];
  await wb.xlsx.writeFile(filePath);return filePath;
}
function addSheet(wb,name,rows){const ws=wb.addWorksheet(name),columns=rows.length?Object.keys(rows[0]):['Thông tin'];ws.addRow(columns);for(const row of rows)ws.addRow(columns.map(column=>row[column]??''));const header=ws.getRow(1);header.font={bold:true,color:{argb:'FFFFFFFF'}};header.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF15785D'}};header.alignment={vertical:'middle',wrapText:true};header.height=30;ws.views=[{state:'frozen',ySplit:1}];ws.autoFilter={from:{row:1,column:1},to:{row:1,column:columns.length}};columns.forEach((name,index)=>{const max=ws.getColumn(index+1).values.slice(1,51).reduce((width,value)=>Math.max(width,String(value??'').length),String(name).length);ws.getColumn(index+1).width=Math.min(Math.max(max+2,12),40);if(/lương|nợ|tiền|nhận|thành_tiền|đơn_giá|số_tiền/i.test(name)){for(let row=2;row<=ws.rowCount;row++)ws.getCell(row,index+1).numFmt='#,##0 "₫"'}});}
function slug(s){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').replace(/[^a-zA-Z0-9]+/g,'-').replace(/^-|-$/g,'')||'cong-nhan'}
function vnDate(s){const [y,m,d]=String(s).split('-');return `${d}-${m}-${y}`}
async function mutate(fn){const d=await readBook(); const result=fn(d);await writeBook(d);return {data:d,result};}
function createWindow(){const win=new BrowserWindow({width:1450,height:960,minWidth:1100,minHeight:720,backgroundColor:'#f5f7f5',webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false}});win.webContents.on('before-input-event',(event,input)=>{if(input.type==='keyDown'&&input.key==='F12'){win.webContents.openDevTools({mode:'detach'});event.preventDefault()}});win.webContents.on('console-message',(_event,details)=>{if(details.level>=2)console.error(`[renderer] ${details.message}`)});win.webContents.on('render-process-gone',(_event,details)=>dialog.showErrorBox('Giao diện đã dừng',`Renderer đã dừng (${details.reason}). Hãy đóng ứng dụng và chạy lại npm start.`));win.webContents.on('unresponsive',()=>console.error('Cửa sổ giao diện Electron không phản hồi.'));win.loadFile(path.join(__dirname,'index.html')).then(async()=>{const source=fs.readFileSync(path.join(__dirname,'app.js'),'utf8');const bootstrap=`(()=>{try{\n${source}\nreturn ''}catch(error){console.error(error.stack||error);return error.stack||String(error)}})()`;const error=await win.webContents.executeJavaScript(bootstrap);if(error){console.error('Không thể khởi chạy giao diện:',error);dialog.showErrorBox('Không tải được giao diện',error)}}).catch(error=>{console.error('Không thể tải trang:',error);dialog.showErrorBox('Không tải được giao diện',error.stack||error.message)});}
app.whenReady().then(()=>{dataDir=path.join(app.getPath('documents'),'QuanLyLuong');fs.mkdirSync(dataDir,{recursive:true});bookPath=path.join(dataDir,'DuLieuLuong.xlsx');createWindow();app.on('activate',()=>{if(!BrowserWindow.getAllWindows().length)createWindow()})});
app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});
ipcMain.handle('data:get',async()=>({data:await readBook(),dataPath:bookPath}));
ipcMain.handle('worker:add',async(_,name)=>(await mutate(d=>{if(!name.trim())throw Error('Vui lòng nhập tên công nhân.');const w={id:id('CN'),name:name.trim(),createdAt:new Date().toISOString(),status:'ACTIVE'};d.workers.push(w);return w})).data);
ipcMain.handle('worker:delete',(_,workerId)=>mutate(d=>{const w=d.workers.find(x=>x.id===workerId);if(!w)throw Error('Không tìm thấy công nhân.');if(d.production.some(x=>x.workerId===workerId&&isPaid(x)))throw Error('Công nhân có dữ liệu đã thanh toán, không thể xóa để bảo vệ lịch sử.');w.status='INACTIVE';audit(d,'DELETE','worker',w,{...w,status:'INACTIVE'});return true}));
ipcMain.handle('product:add',async(_,payload)=>(await mutate(d=>{if(!payload.name.trim())throw Error('Vui lòng nhập tên sản phẩm.');if(!Number.isFinite(+payload.price)||+payload.price<=0)throw Error('Đơn giá phải lớn hơn 0.');const p={id:id('SP'),name:payload.name.trim(),currentPrice:+payload.price,status:'ACTIVE',createdAt:new Date().toISOString()};d.products.push(p);return p})).data);
ipcMain.handle('product:update',(_,payload)=>mutate(d=>{const p=d.products.find(x=>x.id===payload.id);if(!p)throw Error('Không tìm thấy sản phẩm.');if(!payload.name.trim())throw Error('Vui lòng nhập tên sản phẩm.');if(!Number.isFinite(+payload.price)||+payload.price<=0)throw Error('Đơn giá phải lớn hơn 0.');const before={...p};p.name=payload.name.trim();p.currentPrice=+payload.price;audit(d,'UPDATE','product',before,p);return p}));
ipcMain.handle('product:delete',(_,productId)=>mutate(d=>{const p=d.products.find(x=>x.id===productId);if(!p)throw Error('Không tìm thấy sản phẩm.');p.status='INACTIVE';audit(d,'DELETE','product',p,{...p,status:'INACTIVE'});return true}));
ipcMain.handle('production:save',(_,payload)=>mutate(d=>{if(!d.workers.some(x=>x.id===payload.workerId&&x.status==='ACTIVE'))throw Error('Vui lòng chọn công nhân.');if(!payload.lines?.some(x=>+x.quantity>0))throw Error('Không có sản lượng.');const dayRows=d.production.filter(x=>x.workerId===payload.workerId&&x.date===payload.date);if(dayRows.some(x=>x.status==='PAID'))throw Error('Ngày này thuộc đợt đã thanh toán và bị khóa.');let inputs=payload.lines.filter(x=>+x.quantity>0).map(l=>{if(!Number.isInteger(+l.quantity)||+l.quantity<0)throw Error('Số lượng phải là số nguyên không âm.');const product=d.products.find(x=>x.id===l.productId&&x.status==='ACTIVE');if(!product)throw Error('Sản phẩm không còn hoạt động.');return {product,quantity:+l.quantity}});
  let mode=payload.mode||'REPLACE';if(dayRows.length&&!payload.mode)throw Error('DUPLICATE');if(dayRows.length){if(mode==='ADD'){for(const old of dayRows){const line=inputs.find(x=>x.product.id===old.productId);if(line){line.quantity+=Number(old.quantity);line.unitPrice=Number(old.unitPrice);line.existing=old.id}else {const pr=d.products.find(x=>x.id===old.productId);inputs.push({product:pr,quantity:Number(old.quantity),unitPrice:Number(old.unitPrice),existing:old.id})}}}const affected=new Set(dayRows.map(x=>x.periodId));for(const old of dayRows){const i=d.production.findIndex(x=>x.id===old.id);d.production.splice(i,1)}affected.forEach(pid=>updatePeriodDates(d,pid));audit(d,'UPDATE','production',dayRows,inputs)}
  const period=periodFor(d,payload.workerId,payload.date);for(const l of inputs){if(!l.quantity)continue;const price=l.unitPrice??l.product.currentPrice;d.production.push({id:id('PR'),workerId:payload.workerId,productId:l.product.id,productName:l.product.name,date:payload.date,quantity:l.quantity,unitPrice:price,totalAmount:l.quantity*price,periodId:period.id,status:'UNPAID'})}return true}));
ipcMain.handle('production:delete',(_,dateKey)=>mutate(d=>{const rows=d.production.filter(x=>x.workerId===dateKey.workerId&&x.date===dateKey.date);if(rows.some(isPaid))throw Error('Dữ liệu đã thanh toán không thể xóa.');if(!rows.length)throw Error('Không tìm thấy dữ liệu.');rows.forEach(x=>d.production.splice(d.production.findIndex(y=>y.id===x.id),1));audit(d,'DELETE','production',rows,{});const periods=new Set(rows.map(x=>x.periodId));periods.forEach(pid=>{updatePeriodDates(d,pid);const period=d.periods.find(p=>p.id===pid);if(period?.status==='OPEN'&&!d.production.some(x=>x.periodId===pid))d.periods.splice(d.periods.indexOf(period),1)});return true}));
ipcMain.handle('debt:add',(_,p)=>mutate(d=>{if(!d.workers.some(x=>x.id===p.workerId))throw Error('Vui lòng chọn Kỹ sư.');if(+p.amount<=0||!Number.isFinite(+p.amount))throw Error('Số tiền phải lớn hơn 0.');const direction=p.direction==='COMPANY_OWES'?'COMPANY_OWES':'WORKER_OWES';d.debts.push({id:id('NO'),workerId:p.workerId,date:p.date,amount:+p.amount,note:p.note.trim(),direction,status:direction==='COMPANY_OWES'?'CHUA_TRA':'CHUA_TRU'});return true}));
ipcMain.handle('debt:settle',(_,debtId)=>mutate(d=>{const debt=d.debts.find(x=>x.id===debtId);if(!debt)throw Error('Không tìm thấy khoản nợ.');if(debt.direction!=='COMPANY_OWES')throw Error('Chỉ có thể đánh dấu đã trả cho khoản Công ty nợ Kỹ sư.');if(debt.status!=='CHUA_TRA')throw Error('Khoản nợ này đã được thanh toán.');const before={...debt};debt.status='DA_TRA';debt.settledAt=today();audit(d,'SETTLE','debt',before,debt);return true}));
ipcMain.handle('payment:pay',async(_,p)=>{const d=await readBook(),rows=d.production.filter(x=>x.workerId===p.workerId&&x.status==='UNPAID');if(!rows.length)throw Error('Kỹ sư chưa có lương cần thanh toán.');const wage=rows.reduce((s,x)=>s+Number(x.totalAmount),0),selectedIds=new Set(p.debtIds||[]),debts=d.debts.filter(x=>x.workerId===p.workerId&&((x.direction==='COMPANY_OWES'&&x.status==='CHUA_TRA')||((x.direction||'WORKER_OWES')==='WORKER_OWES'&&x.status==='CHUA_TRU'))&&selectedIds.has(x.id)),deduction=debts.filter(x=>(x.direction||'WORKER_OWES')==='WORKER_OWES').reduce((s,x)=>s+Number(x.amount),0),companyDebtAdded=debts.filter(x=>x.direction==='COMPANY_OWES').reduce((s,x)=>s+Number(x.amount),0);if(deduction>wage)throw Error('Số tiền nợ được chọn lớn hơn tiền lương. Vui lòng bỏ chọn một hoặc nhiều khoản nợ.');const pid=rows[0].periodId;if(rows.some(x=>x.periodId!==pid))throw Error('Có nhiều đợt đang mở; vui lòng kiểm tra file dữ liệu.');const pay={id:id('PAY'),workerId:p.workerId,paymentDate:p.date,productionTotal:wage,debtDeducted:deduction,companyDebtAdded,actualReceived:wage-deduction+companyDebtAdded,periodId:pid};d.payments.push(pay);rows.forEach(x=>x.status='PAID');debts.forEach(x=>{x.status=x.direction==='COMPANY_OWES'?'DA_TRA':'DA_TRU';x.paymentId=pay.id});const period=d.periods.find(x=>x.id===pid);period.status='CLOSED';audit(d,'PAYMENT','payment',{},pay);const periodFile=await exportPeriod(d,pay);try{await writeBook(d)}catch(e){if(periodFile&&fs.existsSync(periodFile))try{fs.unlinkSync(periodFile)}catch{};throw e}return pay});
ipcMain.handle('payment:export',async(_,paymentId)=>{const d=await readBook(),pay=d.payments.find(x=>x.id===paymentId);if(!pay)throw Error('Không tìm thấy giao dịch.');await exportPeriod(d,pay);return true});
ipcMain.handle('path:open',()=>require('electron').shell.openPath(dataDir));
